/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./components/Background.vue')['default']
    Clock: typeof import('./components/Clock.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GithubHeatmap: typeof import('./components/GithubHeatmap.vue')['default']
    Hitokoto: typeof import('./components/Hitokoto.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    MusicButton: typeof import('./components/MusicButton.vue')['default']
    MusicPlayer: typeof import('./components/MusicPlayer.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteLinks: typeof import('./components/SiteLinks.vue')['default']
  }
}
